#!/usr/bin/env bash

source /usr/local/bin/terraria-args
arglist=("iid" "user" "invoke")
verify_arglist "${arglist[@]}"

timestamp=`date "+%Y.%m.%d.%H.%M.%S"`
attach="screen -r $user"
inject="screen -S $user -X stuff $invoke^M"

if [ "$invoke" = "attach" ] ; then 
    cmd="$attach" ; 
else 
    cmd="$inject" ; 
fi

if [ "`stat -c '%u' /var/run/screen/S-$user/`" = "`id -u`" ]
then
    $cmd
else
    sudo -u $user $cmd
fi
