#!/bin/bash

echo Checking for root access and scripting errors
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root"
   exit 1
fi
set -e

echo Loading arguments
working_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $working_dir/args.sh

user=terraria-$iid
echo Checking for pre-existing user: $user
if getent passwd $user > /dev/null 2>&1; then
    echo "User $user exists; skipping creation."
else
    echo "User does not exist; creating a new user: $user"
    useradd -rmd /srv/$user $user
fi

echo Configuring paths
shared_dir=$working_dir/shared
terraria_home=/srv/$user/.local/share/Terraria
if $tml_enabled; then
    binary_archive=$(realpath `find $working_dir/tml -type f -name 'tml-*-bin.tar.gz'`)
    version_dir=$working_dir/tml
    world_dir=$terraria_home/ModLoader/Worlds
else
    binary_archive=$(realpath `find $working_dir/vanilla -type f -name 'terraria-*-bin.tar.gz'`)
    version_dir=$working_dir/vanilla
    world_dir=$terraria_home/Worlds
fi

echo Making directories for binaries, scripts, logs, and worlds
mkdir -p /opt/terraria/$iid/bin /opt/terraria/$iid/scripts
mkdir -p $terraria_home/Logs $world_dir
chown -R $user:$user /srv/$user/.local

echo Extracting binaries
pushd /opt/terraria/$iid
tar zxvf $binary_archive
popd

echo Copying scripts
cp -ar $shared_dir/scripts/* /opt/terraria/$iid/scripts/

echo Generating server config from template
server_conf_path=$terraria_home/server.conf
cp $shared_dir/templates/server.conf $server_conf_path
chmod 644 $server_conf_path 
chown $user:$user $server_conf_path

sed "s;{USER};$user;g" -i $server_conf_path
sed "s;{WORLD_DIRECTORY};$world_dir;g" -i $server_conf_path
if [ "$password" == "" ]; then
  sed -i 's;^\(\s*password\s*\)=;\#\1;g' $server_conf_path
else
  escaped_password=$(echo $password | sed -e 's/[\/&]/\\&/g')
  sed "s;{PASSWORD};$escaped_password;g" -i $server_conf_path
fi
if [ "$port" == "" ]; then
  sed -i 's;^\(\s*port\s*\)=;\#\1;g' $server_conf_path
else
  sed "s;{PORT};$port;g" -i $server_conf_path
fi
if [ "$world_name" == "" ]; then
  sed -i 's;^\(\s*world\s*\)=;\#\1;g' $server_conf_path
else
  sed "s;{WORLD_NAME};$world_name;g" -i $server_conf_path
fi

echo Generating service config from template
service_path=/etc/systemd/system/$user.service
cp $shared_dir/templates/instance.service $service_path
chmod 644 $service_path
sed "s;{USER};$user;g" -i $service_path
sed "s;{IID};$iid;g" -i $service_path

if [ "$world_name" != "" ]; then
  echo "Copying world to new instance."
  world_source_path="$shared_dir/worlds/$world_name.wld"
  if [ -f $world_source_path ]; then
    cp $world_source_path $world_dir/
    chown $user:$user $world_dir/*
    chmod 644 $world_dir/*
    echo "Configuring instance to run world: $world_source_path"
  else
    echo "World does not exist: $world_source_path"
  fi
fi
